### ISSUE TITLE
Cordova installation on OSX

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1018]
_From @scooper711 on May 21, 2016 19:7_

Trying to install Ionic CLI on a Mac Air with El Capitan and export my project.  I keep doing the command to install Cordova:

sudo npm install -g cordova

.. and while it indicates that Cordova is getting installed (I run "cordova --version" and it comes back with "6.1.1", after installing Ionic (sudo npm install -g ionic) I keep running the “ionic info” command and it says that Cordova CLI is not installed.

Do I have to configure the $PATH in a certain way to have the Cordova installation recognized?

_Copied from original issue: driftyco/ionic#6605_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related to the Ionic CLI and not the framework I will be moving this issue to that repo. Thanks for using Ionic!

**Comment by jthoms1** [comment]
@scooper711 Could you provide us with the output when you ran ionic info? Thanks

**Comment by scooper711** [comment]
I created a couple of applications (AgriV5 and Agri Farmer) using Ionic Creator.  After building the UI and being satisfied with the emulation I downloaded the code and added a couple of lines of source so that I could see the values for range sliders (there’s no obvious way to get the value for a range component to appear).  After getting the value to appear and being satisfied with the emulation using the “ionic serve” CLI I uploaded the file.  I kept getting the message on the apps.ionic.io site that “this app is not live” but going to the “Getting Started” guide does not help me to figure out how to make it live.  I subsequently uploaded the application again, and the Ionic logo appears next to each instance of the Agri Farmer app name in a different color.  I don’t know whether there’s any significance for different colors, and it’s difficult to tell which is the most recent instance since there is only a date and no time displayed.

I’d like to know the significance of the ionic icon color, how to identify the most recent instance (and why it does not replace the previous instance) and how to make an application live.

In the Ionic Creator world you can create a mobile app and you get a code to pass to users in the team to access the program using the Ionic Creator Mobile App.  I see the Ionic Deploy command in CLI, is this how you   deploy the app to your team members?

I have an app (Agri Farmer) that I built using Creator.  It runs fine on the Creator Preview, but when I export the app and run the commands described in “getting started” and do “ionic serve” I just get a blue band at the top of the browser emulation page.  How do I debug what’s going wrong?

Regards,
Scott

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
