### ISSUE TITLE
Ionic run wrong device

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic-cli#1074]
When I run `ionic run --device android` seems to behave like `ionic run` without arguments.
On OS X it builds and compiles for iOS and tries to run the app on my iPhone, if not present starts a simulator.

`cordova run --device android` works correctly.

I'm using ionic `2.0.0beta.30`

**Comment by jthoms1** [comment]
Could you try switching the order? `ionic run android --device` Thanks!

**Comment by jthoms1** [comment]
Verified this is an issue.  I am working on a fix. Thanks!

**Comment by jthoms1** [comment]
Actually it turns out that the second command argument should be the platform according to cordova's documentation.  http://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-run-command

I would say that the bug is that our documentation within help should indicate that platform should appear before options.

**Comment by jthoms1** [comment]
I am considering this issue closed. Commit 2a3269ba231e165b8454a39924d0c72095e17df3 updates the help code to ensure that we always inform users to supply <PLATFORM> as the first parameter to *run*, *build*, *emulate*, and *platform*. Again thanks for reporting this!

**Comment by Zorgatone** [comment]
Could we support the arguments in the other order too as cordova already does?
