### ISSUE TITLE
why remove js version when using ionic start which make use npm packages so trouble

### ISSUE THREAD

**Issue by gxsjtu** [driftyco/ionic-cli#1137]
cli should keep the parameter to let users make the decision to use which version.

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! We have recently decided to go all in with Typescript because of the awesome advantages it provides to you as an ionic developer. You can read more about that [here](http://ionicframework.com/docs/v2/resources/typescript/). Also if you are having trouble adding libraries to your typescript project I would recommend checking [this](https://www.youtube.com/watch?v=m3tEWHP8WWo) video. Thanks for using Ionic!
