### ISSUE TITLE
Will Ionic State be a part of ionic-cli v3 ?

### ISSUE THREAD

**Issue by dmastag** [driftyco/ionic-cli#1997]
#### What version of the CLI are you using? Output of `ionic --version`

Ionic 3 Beta 

#### Short description of the problem:

The ionic state reset functions are gone

#### What behavior are you expecting?

Is this temporary or will they be removed for certain in Ionic v3 ?

**Comment by jthoms1** [comment]
This will be removed from Ionic v3.  Cordova has made updates so that there is no longer a need for ionic to also track state.  We will be providing documentation on why this was done and how to move forward with plugin/platform state management in cordova.

The short answer is all `ionic plugin/platform add <...>` commands save by default.  In order to restore all plugins/platforms just run `ionic cordova:prepare <platform name>`.

**Comment by rob3c** [comment]
> The short answer is all ionic plugin/platform add <...> commands save by default.

@jthoms1 This still doesn't appear to be the case as of ionic@2.2.2.

I just ran `ionic plugin add cordova-plugin-inappbrowser` in a new ionic 3 sidemenu project. While it did install correctly in the `/plugins` folder and make an entry in the `/platforms/ios/ios.json` file, these are both ephemeral folders - i.e. in the template's `.gitignore` by default. Therefore, there is no 'saved' reference to the plugin in my committed git repo. The next person to clone the repo won't know it was ever added when trying to restore the project.

However, if I explicitly add `--save` to the command above, an entry is created in the root `config.xml` to actually 'save' the plugin for the project.

**Comment by dmastag** [comment]
@rob3c what version of the ionic-cli are you using? Asking since you are mentioning ionic@2.2.2 and my question was about ionic v3

**Comment by rob3c** [comment]
@dmastag oops - good catch! The `ionic-cli` vs `ionic-angular` versioning is a bit confusing, and I didn't read as carefully as I should have. As you noticed, I was using the "ionic 3" library, but only via the "ionic 3" CLI at version 2.2.2. I haven't actually tried cli@3, but hopefully it eliminates the confusion surrounding cordova vs ionic plugin - and more generally, state - management.

**Comment by dmastag** [comment]
Yeahh, thats why I like that in ionic-cli v3 all cordova commands are called using
`ionic cordova:command`

**Comment by alaa-alshamy** [comment]
but `ionic cordova prepare` command doesn't make same as state reset or am i wrong ?

`state reset` command making remove to all platforms and plugins and reinstall and add them again

how can i make something similar in ionic cli v3 ?

**Comment by alaa-alshamy** [comment]
ok i was wrong `cordova prepare` working goodly

the problem was in storing plugins and platforms in package.json file 

it was like old style of ionic , so u should store them either in config.xml or in package.json but with new style of cordova as mentioned here: https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/ 

note: to store in package.json u should use latest cordova cli vesrion >= 7

**Comment by shamank** [comment]
I miss the `ionic state reset --plugins` command. It was very easy to restore plugins or the entire platforms when something wasn't working as expected, specially when you need to use global vars for plugins.
