### ISSUE TITLE
v3-beta8: Adding platform on `ionic cordova` commands automatically could be problematic

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2146]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

Right now it seems some of the `ionic cordova` commands that require a platform to be installed will try to add the platform (`ionic cordova platform add ios/android`) without additional user input. 

On the one side this could be useful as it doesn't require the user to run this command manually, on the other side this doesn't help to educate the user that he actually has to manually add platforms to the project and how it is done.

Example (no Cordova installed, so fails):
```
PS C:\Users\Jan\Documents\beta8test2> ionic cordova run
? What platform would you like to run: ios, android android

> cordova platform add --save android

[ERROR] Command not found: cordova
```
(Additionally the `> cordova platform add --save android` adds to my uncertainty if I should use `ionic cordova` or `cordova` commands...)

#### What behavior are you expecting?

Better output a small error message that tells the user to add the platform manually and shows him the command to do so,

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Go to project directory
3. Run `ionic cordova run android`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by piotrowski** [comment]
Also there seem to be two different ways to handle this right now:

```
PS C:\Users\Jan\Documents\beta8test2> ionic cordova prepare
? You have no Cordova platforms added! Which platform would you like to install (ios, android):
PS C:\Users\Jan\Documents\beta8test2> ^C

PS C:\Users\Jan\Documents\beta8test2> ionic cordova build
? What platform would you like to build: ios, android:
PS C:\Users\Jan\Documents\beta8test2> ^C
```

Once it just asks which platform I want to build and then adds the platform, the other time it recognizes that I don't have a platform and offers to add one.

**Comment by dwieeb** [comment]
Is it not clear that it's running the cordova command under the hood when it prints this out?
```
> cordova platform add --save android
```

I think that's a healthy amount of helpfulness + education. Do you disagree?

**Comment by piotrowski** [comment]
Depends.

Again and again people are confused if they should use `ionic ...` or `cordova`. So when the user uses `ionic cordova ...`, gets an error (see my original post) and then only gets the output of a `cordova` command, this can be confusig.

Maybe replace ">" with "Running: " or something like hat?

**Comment by dwieeb** [comment]
Yeah, I used ">" because it's what npm uses, so people may be familiar with that. I don't quite like how we wrap Cordova either, I know it can be confusing for users. Not sure what the best call is here, I'll investigate

**Comment by Maziar-Fotouhi** [comment]
I am used to removing the contents of my _platforms_ and _plugins_ folders before each deployment.
Currently I'm having two issues with the way this is working:
1. Each time that I run `ionic cordova prepare` for a given platform, it **changes the version numbers** (adds the **caret sign** in front of the version number) of that **platform** and **all of the cordova plugins**, in package.json and config.xml. This is a very frustrating experience for me as a developer because I need to know exactly which version of each plugin is being used in my project and control that. (This only happens when the contents of the _platforms_ folder are deleted, otherwise, it does not add the caret sign).
2. There is no way to add **both** andorid and ios at the same time and you have to run this command twice to add them both. As opposed to the previous experience with `ionic state reset/restore`.

**Comment by dwieeb** [comment]
@Maziar-Fotouhi This doesn't have much to with the original issue... I'm going to create new issues for each of those.

FWIW, the workflow of removing platforms and plugins may be an old workaround to issues Cordova has long since solved.
