### ISSUE TITLE
ionic cordova resources asks for credentials to ionic cloud every time

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2331]
_From @VsMaX on May 22, 2017 11:30_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ionic cordova resources` asks every time for credentials to ionic cloud

**Expected behavior:**
`ionic cordova resources` asks at most ONCE for credentials to ionic cloud

**Steps to reproduce:**
`ionic cordova resources`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2 Build version 8C38
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

_Copied from original issue: driftyco/ionic#11750_

**Comment by piotrowski** [comment]
@VsMaX Did you install ionic with `sudo` or are running some commands with `sudo`?

**Comment by VsMaX** [comment]
No commands with sudo, just tried to run ionic resources and got 404 because my image was too small. Each time I re-tried I had to re-enter my credentials.

**Comment by piotrowski** [comment]
Ok. Does it change if you execute `ionic login` once?

**Comment by VsMaX** [comment]
after one successful upload I did not have problems anymore

**Comment by piotrowski** [comment]
Of `ionic cordova resources` or `ionic upload`?

**Comment by VsMaX** [comment]
`ionic cordova resources`

**Comment by piotrowski** [comment]
Thanks. So probably the credentials are not saved when the `resources` process fails. @dwieeb should be able to fix that ;)

**Comment by VsMaX** [comment]
Yes, I think that is the case, thanks a lot for help!

**Comment by dwieeb** [comment]
@VsMaX @piotrowski This is actually already fixed. The next release comes out soon.

Thanks for the report @VsMaX and @piotrowski for debugging 🎉

**Comment by rapropos** [comment]
Previously, `ionic resources` did not ask for any credentials for anything. I neither have nor want an Ionic Cloud account. Please either make this command work without needing to sign up for anything or provide an alternate way to do whatever it does locally.

**Comment by napolitano** [comment]
Why do i need to login for resource creation? This could be a show stopper for enterprises with strict policies regarding third party cloud services and it might a copyright issue too, if licensed material has to be submitted to a webservice which may or may not immediately delete it.

The resizing of images could be easily done with node modules which can be installed locally. Also altering the config file does not necessarily require a web service. 

So i would kindly ask what's the reason for this significant annoyance which forces me to add some own gulp tasks to do locally what ionic is supposed to do locally. Thank you for clarification.

**Comment by janpio** [comment]
`ionic resources` always worked with a cloud service by the way.

> The resizing of images could be easily done with node modules which can be installed locally. 

Feel free to develop that CLI tool and provide us with its name so we can use it.

**Comment by napolitano** [comment]
I never recognized that it used cloud services. Maybe because of other build chains that generate icons and splash-screens with gulp tasks.

In the past i used:

https://github.com/AlexDisler/cordova-icon
https://github.com/AlexDisler/cordova-splash

Today i thought: Do it the ionic way. For this particular task it was the wrong decision, because i'm not allowed to submit information about projects to third parties - and also resources are considered as such information. Good chance that many developers don't care - but i have to :-/

**Comment by dwieeb** [comment]
@napolitano I made it clear in the resources documentation that it uses our servers. It uses our servers because some users don't want to install heavy image libraries on their computer. For the users that do, I highly recommend those projects. 😄

**Comment by KevRyan2** [comment]
the ionic CLI login is currently not working after updating following this blog post http://blog.ionic.io/ios-11-checklist/ , so by requiring the login it's now not possible for me to run ionic cordova resources... anyone else having issues with the CLI enforced login?

**Comment by raxim1** [comment]
I thought also that ionic 3 does not require logins, but if it is the case, it's a shit, my development time slowed down because of buggy plugins and buggy ionic features.

There is not too much benefit, if i need to pay for this service at some point.

As i need many things, and to be honest the Cordova lib is just a 2-3 weeks job to recreate,
i might jump to native development. Every plugin (i have tried 30-40) what i have used has got so many bugs, that at the end, i had to fix some, and i'm not prepared for IOS development to check everything.
If i need to i would drop my whole 1 year project and start it over to create everything from scratch without ionic without third party libraries and so on. (Nowadays I'm just trying to reduce and recreate some plugins what i have used which shouldn't be the case - the only plugin which worked for me was the FCM one, although partially i have implemented the google api directly)

On the other hand, there is a google infrastructure which makes things more painful.
Too many configuration everywhere, for just some screen and a messaging it needs so enormous work, that i might not finish my project in the next decade.

Messaging system is not that flexible, and at the end you are just dealing with a new third party service firebase, but it's not reliable. So you need some sort of javascript background service on android to ignore this whole notification nightmare.

**Comment by Domvel** [comment]
I didn't read all posts, but ... This should be available offline a part of ionic and not a online service. wtf? sorry, but I can't understand this. It's just a image resize batch. But np, I gonna write my own resource batch script with blackjack and .. you know?

**Comment by dwieeb** [comment]
[Ionic CLI 5](https://github.com/ionic-team/ionic-cli/blob/develop/packages/ionic/CHANGELOG.md#500-2019-05-29) ships with support for generating Cordova resources locally using the [cordova-res](https://github.com/ionic-team/cordova-res) utility, which completely replaces the existing code for generating resources remotely in `ionic cordova resources`.

Give it a try! Leave feedback/bug reports in either repo. Thanks!
