### ISSUE TITLE
bug: deviceready has not fired after 5 seconds

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#259]
_From @mccob on February 13, 2015 16:33_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>browser</span>

<span ionic-description>With last stable versions of crosswalk, ionic and cordova, got "deviceready has not fired after 5 seconds" error
and Cordova API are unusable.</span>

<span is-issue-template></span>

Crosswalk developer say to open bug on ionic tracker : https://crosswalk-project.org/jira/browse/XWALK-3345

_Copied from original issue: driftyco/ionic#3108_

**Comment by adamdbradley** [comment]
https://crosswalk-project.org/jira/plugins/servlet/mobile#issue/XWALK-3345

**Comment by FabioAntunes** [comment]
This also happens to me with Lollipop. Today I added crosswalk and with it live reload doesn't work, after a git reset --hard HEAD (to remove crosswalk) everything works fine

**Comment by bleuscyther** [comment]
Same thing here
http://forum.ionicframework.com/t/ionic-cli-livereload-causes-errors-deviceready-has-not-fired-after-5-seconds/10713/10

**Comment by ratt** [comment]
This only appears to be an issue with --livereload. If i compile and run normally then everything works as expected. If i ionic run --livereload android then i keep getting 

0     490982   log      deviceready has not fired after 5 seconds.
1     490983   log      Channel not fired: onFileSystemPathsReady
2     490984   log      Channel not fired: onCordovaConnectionReady

**Comment by bleuscyther** [comment]
@ratt  true

**Comment by HriBB** [comment]
Same here. ionic run android -l gives

cordova.js:1183 deviceready has not fired after 5 seconds.
cordova.js:1176 Channel not fired: onFileSystemPathsReady
cordova.js:1176 Channel not fired: onCordovaConnectionReady

**Comment by tobika** [comment]
@ratt can confirm this aswell

**Comment by aszmyd** [comment]
@ratt same here. Without --livereload works fine, with it - not

**Comment by honomoa** [comment]
I have the same issue.

I install two plugin below:
cordova plugin add https://github.com/wymsee/cordova-HTTP.git
cordova plugin add org.apache.cordova.file

it appears:
cordova.js:1183 deviceready has not fired after 5 seconds.
cordova.js:1176 Channel not fired: onFileSystemPathsReady

maybe the cordova-HTTP  use old version of org.apache.cordova.file and conflict with new version of org.apache.cordova.file

**Comment by mlynch** [comment]
Take a look at this, it fixes the issue for me: http://christian.fei.ninja/Solution-to-PhoneGap-issue-device-ready-has-not-fired-after-5-seconds/

**Comment by mattezell** [comment]
Unfortunately @mlynch, I am unable to perform the 'add android' discussed in the linked article due to the following error:
Failed to install 'org.crosswalk.engine':CordovaError: Plugin doesn't support this projects cordova-android version. cordova-android: 3.6.4, failed version requirement: >=4.0.0-dev

'ionic start' includes android-cordova v.3.6.4 by default currently.  Running 'cordova platform remove android' and then 'add android' as mentioned bombs due to the inclusion of crosswalk... 

To get things back base level operational, you have to 'ionic remove browser crosswalk' before you can again run the 'cordova platform add android' without the above error... 

Which of course takes us back to the initially reported problem.

**Comment by angusyoung84** [comment]
I removed and re-added the plugins through cordova plugin remove / add <plugin> and stopped getting this error message.

**Comment by hasandogu** [comment]
I am having this issue only when I install the file plugin:

deviceready has not fired after 5 seconds.
cordova.js:1162 Channel not fired: onFileSystemPathsReady

Also, I am using Ripple and not the ionic-cli and I don't have Crosswalk but this is happening on the device and Chrome.

I tried removing and re-adding all the plugins as well as the latest versions of the file (2.0.0) and file-transfer (1.0.0) plugins but I am still getting the error.

**Comment by privatebasim** [comment]
ya mennnnaaaaaaaaaaaaaaaaaaaaaaa :D

**Comment by programmarchy** [comment]
I've run into this issue a few times because my livereload script was pointing to the wrong IP. Sometimes I had set the IP to a LAN address to test on a real device, and was still trying to use this IP for local development later once my IP changed. Using the correct IP prevents this issue.

**Comment by manoj529** [comment]
I'm not sure where and why this error is occurring, However in my case issue resolved by removing platform using command 
cordova  platform remove android
cordova  platform remove ios

and then adding them again.

**Comment by ituhin** [comment]
I am also having this issue in ios 
i build it in xcode 7 and tried it in simulator and device

I noticed things starts moving when I press the home button and comes out, 2nd time when i go inside app its already loaded. anyone experiencing this ?

from my xcode error console ==>
[33174:1836465] deviceready has not fired after 5 seconds.
[33174:1836465] Channel not fired: onCordovaInfoReady
[33174:1836465] Channel not fired: onCordovaConnectionReady

$ionic info 
Cordova CLI: 5.2.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.0 Build version 7A176x

**Comment by ituhin** [comment]
ok. for me this got solved after modifying 
<meta http-equiv="Content-Security-Policy" ....

**Comment by growthclick** [comment]
@ituhin Thanks so much! I was stuck on the same issue where Xcode debugger's console seemed to stop after "Finished load of", and it would only resume after I swiped out of the app momentarily. The issue was that my Content-Security-Policy tag was too strict (initially set up for Android).  

I had the same behavior. The security issue also caused Cordova plugin calls (like Camera and Imagepicker) to be delayed. They only triggered when swiping out (e.g. to adjust brightness) and then back into the iOS app.

**Comment by ituhin** [comment]
:+1:  :)

**Comment by siphiwe** [comment]
@ituhin / @growthclick would you please share what your meta tag looks like? I have this but it's not helping: 
```html
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
```

**Comment by ituhin** [comment]
@siphiwe try removing this one if you have it 
<meta http-equiv="Content-Security-Policy" ...

if you dont have it then your problem is something else. try safari/chrome remote debugger to figure out the issue.

**Comment by siphiwe** [comment]
I do need a Content-Security-Policy meta tag. It's required by  the cordova-plugin-whitelist plugin. By the way, I had pasted the wrong tag in my previous comment, I just corrected it as follows:
```html
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
```
For the record, if I do remove this tag, I still get the problem with deviceready not firing within 5 seconds. Chrome developer tools only reveals csrf problems which I'm ok with because localhost is trying to make requests to my server.

**Comment by growthclick** [comment]
If the priority is iOS, then removing the Content-Security-Policy should solve the problem (you can still keep the Cordova-plugin-whitelist in place), and you can use Safari remote debugging to clarify other issues.  For Android, the Content-Security-Policy seems to be required (for ionic run android), otherwise I was getting a white screen when trying to debug with "ionic run android".

Here is a Content-Security-Policy that I'm using on iOS (it's a google maps project). This version may not be tight enough security wise but it's working for me right now on iOS development. 

```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self'  http://*.googleapis.com
     https://*.googleapis.com http://*.gstatic.com https://*.gstatic.com
    'unsafe-inline'; script-src 'self'  http://*.googleapis.com
    https://*.googleapis.com http://*.gstatic.com https://*.gstatic.com 'unsafe-inline' 'unsafe-eval'">
```
The other thing to check for (with Cordova Whitelist) is that you specify access origin in your project's config.xml: 

     <access origin="*"/>  

The above may not be secure enough for a production project - check out https://cordova.apache.org/docs/en/4.0.0/guide_appdev_whitelist_index.md.html for details. 

Hope that helps!

**Comment by deceadmin** [comment]
I did face the same problem with device-motion plugin. When I remove it or stop calling it from the app it works without any problem

**Comment by ituhin** [comment]
@siphiwe for me its this.... i had to add ws: and wss: for websockets in my app, and in ios it was crying for gap: 
i have something like this
<meta http-equiv="Content-Security-Policy" content="default-src 'self' https:; connect-src 'self' wss://*.xyz.com ws://*.xyz.com https://*.xyz.com https://*.xyz.com ws://localhost:35729 gap:; style-src 'self' 'unsafe-inline' gap:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: gap:; frame-src https://*.xyz.com gap: localhost">

**Comment by siphiwe** [comment]
Thanks for assistance guys. I have tweaked the Content-Security-Policymeta tag and got no joy. I just noticed that this issue doesn't occur on IOS. Well, I'm testing with Intel XDK emulators. It's on Windows and Android emulators that I get this.  Am a bit stumed at the moment.

**Comment by siphiwe** [comment]
For what it's worth, I have now trimmed the whole thing down to a brand new Ionic project (using the tabs template), and put $ionicPlatform.ready in the app.run method and this bug popped up. It's only on IOS that the problem does not happen. I have created this setup both on Ubuntu 14.4 and on Windows 7. Not sure if it's a version mismatch between Ionic itself and plugins, cordova, etc. (How do people manage version compatibility reliably, anyway? Is bower the preferred way to take care of this?)

Essentially, I can't do a simple "Hello world" with a platformReady event. No idea what to do now. Any assistance would be appreciated. Thanks

**Comment by ituhin** [comment]
@siphiwe ... try with remote debugging in chrome. you might get more info regarding error

**Comment by jayvi** [comment]
Hi for everyone.  I had the same problem and i jsut solve it : 

1. use yo ionic  https://github.com/diegonetto/generator-ionic
2. Choose blank project 
3. Copy - Paste my template folder with index.html and scripts
4. sudo ionic platform ios 
5. sudo ionic build ios
6. ionic emulate ios  --livereload 

and thats it.

I hope i help to someone with this.

**Comment by mlynch** [comment]
Hey everyone. Often, the issue is a bad plugin install that is holding up
device ready. I find that what usually works is removing my other plugins
(ionic plugin rm cordova-plugin-statusbar for example), and adding them
back.

We are trying remove this error or be louder about it by going a bit deeper
in Cordova, but we're not there yet.





Max Lynch
Chief Executive Ion
max@ionic.io
414-530-9687
_______________________________________________________
ionicframework.com | @ionicframework <http://twitter.com/ionicframework> | 121
S. Pinckney st. Ste 300 Madison, WI 53703

**Comment by mariobb** [comment]
Still same problem here...
I figured out that happend, to me, only the first time i open up the app. With no data nor cache.
On Android

**Comment by wargun02** [comment]
For me, its definitely the Content-Security-Policy which was causing the issue in iOS. Yes, I do need the Content-Security-Policy to run for Android as well. So what I did as a work around was to have a bash script to inject the meta Content-Security-Policy tag into the index.html if I need it to build and run on Android and not to have it injected for build and running on iOS.

**Comment by helloworld3q3q** [comment]
now  I  get this trouble,  but how can I  solve it, Who can tell me???thank a lot

**Comment by saurabhudaniya200** [comment]
I too have this problem (only on some android devices), is there any update on this one?

My plugin are as follow

com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-crosswalk-webview 1.7.2 "Crosswalk WebView Engine"
cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-social-message 0.4.0 "Social Message"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
ionic-plugin-keyboard 2.2.1 "Keyboard"


I am using cordova 6.3.1

**Comment by bayanAbuawad** [comment]
When you develop a hybrid application with PhoneGap, Cordova, Ionic, CordovaChromeApps and any other framework that is built on top on PhoneGap, I can almost assure you that you’ll get this error. And it’s super annoying.

I think the issue is when you delete your platforms folder, or the files inside, and do a platform add ... afterwards. This is at least how I reproduced it.

You’ll need to:

1) add the platforms with cordova platform add ios android

2) remove them with cordova platform remove ios android

3) add them again.

I know this is super weird, but I think it’s related to a faulty android.json and ios.json inside the platforms folder.

Following the steps above fixed the issue for me :).

**Comment by snehasis** [comment]
Any Update on this issue ?, this seems to happen on some of the android devices as well still.
Ionic 2 RC 2 also having the same issue

**Comment by stchoukeu** [comment]
Same problem for me with Ionic RC 3. Any Update? Please i need help

**Comment by KaFu61** [comment]
Same problem here (RC 3)

**Comment by mlynch** [comment]
I'm going to lock this so people don't miss @bayanAbuawad's instructions above. 99% of the time the issue is a plugin that is in an inconsistent state. Try removing your plugins and your platforms and re adding them.
