### ISSUE TITLE
Do not mock cordova.js file if it exists

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic-cli#277]
Hi,

I'm using the cordova.js file to mock plugins behaviours during browser development (https://github.com/loicknuchel/ionic-starter/blob/master/www/cordova.js).
When I'm using `ionic serve` the local server do not serve my cordova.js file but serve an empty mock file (https://github.com/driftyco/ionic-cli/blob/dd1085b1bf66f6ee69c90d90355d12f9a34d01ff/lib/ionic/serve.js#L247).

It could be nice to serve this mock file (to prevent 404 error) only if it doesn't exists or, at least, to give a option to desactivate this feature.

Thanks !

**Comment by phasnox** [comment]
+1

**Comment by loicknuchel** [comment]
An other thing, insted of injecting an empty cordova.js file, you could inject a cordova.js file containing plugin mocks...
If you do so, browser development will be **a lot easier**...

I can make some pull-requests for mocks of common plugins :)

**Comment by lewisl9029** [comment]
Unless I'm mistaken, I believe this issue also prevents Cordova plugins from being able to work under `ionic run --livereload` since ionic can't serve a valid cordova.js or cordova_plugins.js even if we copy it into the directory.

I'll see if I can get a `--disable-cordova-mock` flag working, since I'd like to be able to use plugins with `ionic run --livereload` if possible.
