### ISSUE TITLE
ionic login followed by ionic upload uses previously entered credentials

### ISSUE THREAD

**Issue by SashaGeekette** [driftyco/ionic-cli#297]
Used ionic login to enter email and password
Got message "Logged in! ;)"
Used ionic upload a few times. Worked fine.
Now used ionic login and entered a different set of credentials
Got message "Logged in! ;)"
Used ionic upload. Uploaded to my first account and not to the account specified with the most recent credentials.
I am using CLI version 1.3.14 (latest version)

Workaround: Explicitly use the -e and -p flags when running ionic upload to specify the new credentials.

**Comment by DEllingsworth** [comment]
Additional information:

**To clear your credentials**: clear the file .ionic\cookies.data that is stored at:
process.env.HOME || process.env.USERPROFILE || process.env.HOMEPATH
For windows this is likely c:\user\<username>\.ionic

However,**upload** behaves in a way I don't think the user expects.
Once logged in successfully, the app is uploaded to the user's account that the Ionic.io server associated with the app_id value stored in ionic.project. Even if that logged in user has no association with that app_id.

For example:

ionic upload -email user1@c.com -password hackme
Iogin to ionic.io as user1 and see the new project
delete project from ionic.io using web interface

ionic upload -email user2@c.com -password hackme2
login to ionic.io as user2 and see NO project listed
login to ionic.io as user1 and see project listed

The workaround is to manipulate the app_id value stored in ionic.project when you want to change users.

I suggest that the server side code be modified to allow uploads only when the project ID AND associated email matches.  Otherwise a new project ID should be created.
