### ISSUE TITLE
Create new starters from Plnkr

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#299]
Plnkr just added an endpoint so we can download any public plnkr as a zip:
http://api.plnkr.co/plunks/plunkId

Let's add this as another way to start ionic apps:
https://github.com/driftyco/ionic-cli#starting-an-ionic-app

**Comment by ggoodman** [comment]
To clarify, you *NEED* to affix a `.zip` to that endpoint or you will be getting a json payload.

**Comment by adamdbradley** [comment]
Sweet thanks:
http://api.plnkr.co/plunks/XlxcY0su29QSGNOUZeFm.zip

**Comment by jbavari** [comment]
@ggoodman First off, thanks for supplying this! This is awesome stuff!

I'm trying this out and it's working half of the time. 

When I try the link @adamdbradley posted, it unzips to give me a single file - `XlxcY0su29QSGNOUZeFm.zip.cpgz`

However, when I try another link - `http://api.plnkr.co/plunks/BZrnKPlCJt93orQp58H3.zip` - it unzips correctly.

Could this be due to permissions? Adam also seems to get the `cpgz` file as well.
