### ISSUE TITLE
Add an option in order to not create hooks

### ISSUE THREAD

**Issue by rpignolet** [driftyco/ionic-cli#315]
In my project I don't use the ionic hooks.
Is it possible to add an option in order to not create hooks when running ionic commands ?

**Comment by jbavari** [comment]
This is something I've added to my list to look at. I just hadn't gotten to it yet. 

Due to the latest release of cordova, some of these functions happen now without these hooks. Thus, it's time to remove the hooks and let cordova do its thing.

I'll be addressing this fairly soon. I'd love any help in the meantime!

**Comment by jbavari** [comment]
@rpignolet - thanks again for the submission. I'll be merging this to master soon. Also, some of the plugin hooks have been removed since cordova provides this. :)

**Comment by rpignolet** [comment]
No problem, glad to help you :wink:
