### ISSUE TITLE
bug: How can I install plugins on add platform?

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#334]
_From @umbrella-anton-kramazin on March 26, 2015 7:16_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>After update ionic-cli (ver 1.3.18) was been removed hook 'after_platform_add', who added 'cordovaPlugin' from package.json. How can I install plugins on add platform now?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3407_

**Comment by perrygovier** [comment]
_From @walski on March 26, 2015 13:25_

:+1:

**Comment by jbavari** [comment]
@umbrella-anton-kramazin - you're right.

Theres a `--save` argument that cordova has to save plugins and platforms to the `config.xml` file. 

At first my idea was to remove these plugins (since users have had some issues with them) and let cordova do its thing.

However, after using the cordova feature, I'm not really happy with it.

I'll leave this issue open to have a reference - we need a method `ionic save` or `ionic restore` that will keep these settings for plugins and platforms and add them appropriately.

**Comment by walski** [comment]
@jbavari Sorry if this is drastic but: Are you folks serious?!

I understand that Ionic is still not 100% production ready but making your CLI basically removing hooks from existing projects only to let them end up in a state where they plainly don't work anymore once you have to reinstall a platform... that is an interesting decision.

I'm really happy with all the effort you put into Ionic and definitively are a big fan of many of things you are approaching. But it's moves like this one that make Ionic feel like a toy rather than a tool :/

Sorry just had to get this off my chest. Keep up the good work and please be a bit more considerate about breaking changes (this is even worse at there basically is no way to stop the CLI from removing my hooks over and over again) like that in minor version updates in the future.
