### ISSUE TITLE
Add CLI command to print all AngularJS routes

### ISSUE THREAD

**Issue by mark-veenstra** [driftyco/ionic-cli#383]
Wouldn't it be great to have an Ionic CLI command that prints all the configured AngularJS routes of the application?

**Comment by jbavari** [comment]
This sounds like a great feature. 

One question I'd have to ask - how would we know where those routes are stored?

For the most part, we have a convention that most template apps have the `app.js` file that stores the routes.

However, theres nothing stopping most users from putting routes in a different location. Most may do just that based off of their preferences.

I'm assuming you're referring to the feature like `rake routes` that shows you all of those routes. Since there isn't a set-in-stone convention for the routes, it doesn't look like this will work for *all* of the Ionic users.

Any suggestions?

**Comment by mark-veenstra** [comment]
I have been thinking for a while since I posted this suggestion. But I am not sure yet which way would be best.

For example within in the Ionic/AngularJS project you could use `$state.get()` to get all defined routes. If you could load the project and inject this part to get the states I believe it would cover all users.

Another, not the best, approach could be to do some kind of scripting searching for all files containing `$stateProvider` and process these files to get all routes.

**Comment by mark-veenstra** [comment]
http://stackoverflow.com/questions/21590466/see-what-states-are-configured-in-ui-router
