### ISSUE TITLE
Question: Can I run 'ionic serve' as linux service?'

### ISSUE THREAD

**Issue by dejancencelj** [driftyco/ionic-cli#446]
Hello!

Is it possible to start ionic serve as deamon? I would like to deploy on server and want the service to stay up even when I disconnect fssh session.

Cheers

**Comment by adamdbradley** [comment]
Greetings @dejancencelj!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
