### ISSUE TITLE
ionic build android error

### ISSUE THREAD

**Issue by thierce** [driftyco/ionic-cli#447]
Error:
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
ERROR building one of the platforms: Error: C:\app\tests\ionic\on
first\platforms\android\cordova\build.bat: Command failed with exit code
1
You may not have the required environment or OS to build this project
Error: C:\app\tests\ionic\first\platforms\android\cordov
a\build.bat: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\Andrew\AppData\Roaming\npm\node_modules\c
ordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

ionic info:
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Windows 7 SP1
Node Version: v0.12.4

**Comment by adamdbradley** [comment]
Greetings @thierce!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
