### ISSUE TITLE
Ionic white screen when app launched from  multitasking bar 

### ISSUE THREAD

**Issue by reviloera** [driftyco/ionic-cli#448]
When I select my app from the multitasking panel on android , a white screen covers the app and if a touch the screen it fades a way . All my ionic apps are behaving that way , Am testing on android 4.3

**Comment by adamdbradley** [comment]
Greetings @reviloera!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
