### ISSUE TITLE
ionic run and ionic emulate not working (Windows 8.1)

### ISSUE THREAD

**Issue by fals** [driftyco/ionic-cli#456]
I can't run my Ionic app, both commands *ionic run* and *ionic emulate* returns:

**Updated the hooks directory to have execute permissions**

- Ionic-cli:  CLI v1.5.0

**Comment by fals** [comment]
My computer setup:

...
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
OS: Windows 8
Node Version: v0.10.33
...

**Comment by adamdbradley** [comment]
Greetings @fals!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
