### ISSUE TITLE
Livereload not reloading application

### ISSUE THREAD

**Issue by mrblackus** [driftyco/ionic-cli#460]
Hi !
I tried to use live reload feature with `ionic serve` and `ionic emulate ios --livereload`. Server starts well, application is displayed on simulator (or in browser) and it works smoothly.

When I change a file (a js or html in `www` directory) and save it, console write `HTML changed: www/index.html` for example, but application doesn't reload itself as it should be.

I supposed that websocket between server and app could be broken, but when I kill the server (Ctrl-C), web inspector immediatly fire the following error :
`[Error] WebSocket network error: The operation couldn’t be completed. Connection refused (192.168.5.2, line 0, x4)`

So I supposed that there is no issue with websocket. Moreover, it is displayed with no error in Network pane of web inspector.

Is there something I missed to made livereload work ?

My configuration :
Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.30
Xcode version: Xcode 6.3.2 Build version 6D2105 

Don't hesitate to ask me for clarification if something is not clear.
Thanks in advance !

**Comment by jamiegood** [comment]
Hi there, 
do you have a proxy environment variable set I.E. $http_proxy 

I had and live reload was not working. But when I removed that proxy env variable it started working again.

**Comment by adamdbradley** [comment]
Greetings @mrblackus!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
