### ISSUE TITLE
Windows platform on lab

### ISSUE THREAD

**Issue by CKGrafico** [driftyco/ionic-cli#464]
How can I help to add windows phone as platform on ionic lab?

**Comment by adamdbradley** [comment]
Greetings @CKGrafico!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
