### ISSUE TITLE
Adding Android to Project don't work without version

### ISSUE THREAD

**Issue by loose11** [driftyco/ionic-cli#468]
I run into a issue with my OS X system. After the setup of a new Ionic project, I wanted to add the Android platform. 

```
ionic platform add android
```

But it doesn't happened anything, no helpful error log. Only this two lines:

```
Updated the hooks directory to have execute permissions
Saving platform to package.json file
```

My env-variables are set all correct and thats my "ionic info"
```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.5
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: Not installed
ios-sim version: 1.9.0
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105
```

After a while of trying I added the version number of the android platform behind the command and it worked. 

```
ionic platform add android@4.0.2
```

Did I miss something in the document or is this a little bug of the "platform add" command?

http://stackoverflow.com/questions/30682658/cant-add-android-platform-to-ionic-project

**Comment by adamdbradley** [comment]
Greetings @loose11!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
