### ISSUE TITLE
Named starter templates JSON file is incomplete

### ISSUE THREAD

**Issue by rbose85** [driftyco/ionic-cli#474]
The starter templates are listed in a [JSON file](http://code.ionicframework.com/content/starter-templates.json). This is a list of 7 starter projects, but a total of 10 exist. 

![1433850513752](https://cloud.githubusercontent.com/assets/2758507/8057063/01b66b78-0ea6-11e5-9fec-8c8966d331c8.png)

**Comment by adamdbradley** [comment]
Greetings @rbose85!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
