### ISSUE TITLE
Can't install with shrinkwrap resolved urls

### ISSUE THREAD

**Issue by johnrc** [driftyco/ionic-cli#476]
I use npm enterprise to resolve dependencies and sit behind a proxy so when I do an `npm install -g ionic` I get `getaddrinfo ENOTFOUND` when resolving and installing dependencies. This seems to occur because of `npm-shrinkwrap.json`'s hard coded `resolved` urls. [This issue on npm](https://github.com/npm/npm/issues/3581) seems to address the root cause. In the meantime, could we remove the `resolved` urls or something like that?

The only workaround I have right now is to run `npm install -g --no-shrinkwrap ionic@1.2.x`.

**Comment by adamdbradley** [comment]
Greetings @johnrc!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
