### ISSUE TITLE
How gulp-sass makes scss/ionic.app.scss root directory to project root?

### ISSUE THREAD

**Issue by atom2ueki** [driftyco/ionic-cli#479]
Recently I've change the gulp config to use gulp-compass instead of gulp-sass, but what I have to do is change this line `@import "www/lib/ionic/scss/ionic";` to `@import "../www/lib/ionic/scss/ionic";` inside scss/ionic.app.scss file, don't know how could gulp-sass find the correct relative path for `www/lib/ionic/scss/ionic` firstly.

**Comment by adamdbradley** [comment]
Greetings @atom2ueki!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
