### ISSUE TITLE
Error while toke authentication.

### ISSUE THREAD

**Issue by mhd999** [driftyco/ionic-cli#492]
After i integrate crosswalk to existing ionic app login in via google+ and facebook Cause app crashing, however login via email working fine when it's also based on token authentication. is it something to do with SSL !

**Comment by adamdbradley** [comment]
Greetings @mhd999!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
