### ISSUE TITLE
Feat: Ability to add any crosswalk version I pass

### ISSUE THREAD

**Issue by Stiveknx** [driftyco/ionic-cli#496]
Since all crosswalk sources are downloaded from:
https://download.01.org/crosswalk/releases/

I think I could download exactly the version I want..
Let's say, the latest canary version in ionic (1.5.4), is: 14.42.334.0

But In crosswalk releases, version 14.43.343.0 is already available:
https://download.01.org/crosswalk/releases/crosswalk/android/canary/14.43.343.0/

I don't see any reasons for me to only use version 14.42.334.0, since I can ask for the version 14.43.343.0, that I know that is available.

Of course, this would be an "advanced" feature, for only people "Who knows what they're doing", but I think it would be usefull for someone who wants to try a different crosswalk version, not only the available versions ...

**Comment by jbavari** [comment]
If you are using Cordova CLI 5.0+, they support Crosswalk directly with the official plugin. There is no more need to use Ionic CLI to do this. 

The Ionic CLI provides installation of the official plugin with a few other supported plugins as a convenience to our users.

[See these instructions on how to specify a version.](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#configure)

Due to that, we will not be focusing on the `browser` feature in the current time. 

I'd be happy to review any pull requests you'd be kind enough to offer, though!

**Comment by Stiveknx** [comment]
I've been using cordova's own crosswalk support, but then don't support crosswalk-lite ;/
