### ISSUE TITLE
platform add with multiple platforms doesn't add to package.json

### ISSUE THREAD

**Issue by Deminetix** [driftyco/ionic-cli#518]
If i run `ionic platform add ios android` only ios gets added to the package.json file

**Comment by adamdbradley** [comment]
Greetings @Deminetix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
