### ISSUE TITLE
ionic add should inject dependencies to index.html 

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic-cli#522]
i have a suggestion ```ionic add <component>``` should inject dependencies directly in index.html

**Comment by jaszczur171** [comment]
You can get that working very quickly with gulp and gulp-inject

**Comment by digitaldrummerj** [comment]
I have a blog post on how to setup gulp-inject with ionic at http://digitaldrummerj.me/gulp-inject/

**Comment by adamdbradley** [comment]
Greetings @programming-kid!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
