### ISSUE TITLE
Totally offline mode, boys!

### ISSUE THREAD

**Issue by xuelvming** [driftyco/ionic-cli#527]
I was attracted by ionic when I tried to do take a try of Cordova, But I found a really bad feature in ionic. The cordova support all the offline mode for plugins, platforms,project creation.. While the ionic has to connect the internet and download the same content again and again. For example, the Master.zip. 
Hope you guys can solve this issue soon. We don't have internet every moment . Thanks, guys.

**Comment by jbavari** [comment]
In a perfect world, this would be great. Most of what the CLI does requires dynamic data from the server.

It would take some work to get the wrapper and starters pre-downloaded and cached. There are also the default resources that come along with the CLI, which also must be retrieved.

Any ideas how to have dynamic data cached in the tool while you *do* have internet access?

**Comment by adamdbradley** [comment]
Greetings @xuelvming!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
