### ISSUE TITLE
Chrome debugging not working

### ISSUE THREAD

**Issue by kaumac** [driftyco/ionic-cli#531]
I don't know what happened, but my apps are not being recognized by chrome://inspect anymore.

I'm on a Moto X XT1068 (2013)  running lollipop 5.1.
I'm using the latest versions of Ionic and Cordova (just updated everything and started a blank app).

Dev mode and debugging enabled and usb cable connected.
I have tried with and without using crosswalk.

It's reeeeally painful to debug using 'adb logcat'.

**Comment by baleboy** [comment]
What version of Chrome do you use to debug?

**Comment by adamdbradley** [comment]
Greetings @kaumac!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
