### ISSUE TITLE
without -livereload, app on device(ios/android) can't access to www/img and www/html

### ISSUE THREAD

**Issue by fkkcloud** [driftyco/ionic-cli#533]
I guess its related to access local resources with -livereload

Running with..

ionic emulate ios -livereload -c

Every resource are loaded good.

But when I run without it.. like so.

ionic emulate ios -c

It shows below errors like below..

[Error] Failed to load resource: The requested URL was not found on this server. (X_Marker.png, line 0)
[Error] Failed to load resource: The requested URL was not found on this server. (window.html, line 0)

I am putting the img in www/img and template html for ng-directive in www/templates.

Calling image or html as below.

   var imagePost = {
            url: 'img/Default_Marker.png',
            size: new google.maps.Size(100, 100),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(1, 1)
        };
or for html,

return {
    restrict: 'A',
    templateUrl: '/templates/window.html',
    link: link
};

I was looking all over stackflow, google and ionic forums but no answers but lots of same problem posted..

Here goes the link to this issue with pictures.. Please let me know what is to fix it...

http://forum.ionicframework.com/t/is-there-a-specific-way-to-manage-resource-for-ionic-app/29162

**Comment by adamdbradley** [comment]
Greetings @fkkcloud!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
