### ISSUE TITLE
ionic keyboard does not shift the view until I actually type something. (view should be shifted as I give focus to the input element, no?)

### ISSUE THREAD

**Issue by fkkcloud** [driftyco/ionic-cli#534]
Hi,

ionic keyboard does not shift the view until I actually type something. (view should be shifted as I give focus to the input element, no?)

I've installed ionic keyboard plugin as below.

ionic plugin add com.ionic.keyboard
When I run it on devices, (ios and android) and give focus to input element by touching on it. keyboard comes up but the view is not shifting upwards..

Once I start to type something, then the view shifted as well as ng-focus attribute of input element as well.

    <form ng-controller='PostsCtrl' name='postForm' novalidate>
      <input type='text' 
          ng-model='content' 
          ng-focus='someFunc()'
          maxlength='20' 
          class='postbox'
          id='map-post-input' 
          placeholder='Why its not working?' required>
      <button ng-disabled='postForm.$invalid' 
          ng-click='addPost()' 
          class="postbox button button-small button-assertive" 
          id='map-btn-submit'> {{ timevalue | date:"mm : ss" }} </button>
    </form>
and this elements are added on top of Google Map if that is related information as well..

What could possible go wrong?

**Comment by adamdbradley** [comment]
Greetings @fkkcloud!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
