### ISSUE TITLE
Ability to specify cordova plugin versions

### ISSUE THREAD

**Issue by fabiosussetto** [driftyco/ionic-cli#535]
Hi, I haven't found a way to pin down a specific plugin version with $ ionic state save or $ ionic plugin add
I believe this is a real necessity in order to have reproducible builds on different machines at different times. Any plans to support this? Is it already implemented, but not documented? 

Thanks.

**Comment by deebloo** [comment]
if you add do ```ionic plugin add com.myplugin.www``` it will save the plugin to the confix.xml file

**Comment by adamdbradley** [comment]
Greetings @fabiosussetto!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
