### ISSUE TITLE
Update ionic-app-lib sass watch patterns according to ionic.project

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic-cli#536]
Hello Ionic Team, fist of all good job on the framework, ionic.io and cli! 
A while ago there was a discussion about a 'production' build option to be provided in the ionic ecosystem that would offer uglification, magnification, and concatenation. Please see following issues for more info #168 and #270 
However this really important feature that is must have for enterprise and public apps that reduces safety concerns for hybrid dev shops lost its momentum... So that said many of us just rolled our own scripts.
Enough of that...
After defining an alternate document root and watch patterns in `ionic.project` like so:
```
{
  "name": "tabsTest",
  "app_id": "",
  "documentRoot": "app",
  "createDocumentRoot": "app",
  "watchPatterns": [
    "app/js/*",
    "!app/css/**/*"
  ],
  "gulpStartupTasks": [
    "sass",
    "watch"
  ]
}
```
I noticed that if `www` folder is empty I am getting following error from the cli:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: source string:22: error: file to import not found or unreadable: "www/lib/ionic/scss/ionic"

```

After some investigantion I determined that there are hard coded sass patterns that point to `www` folder in https://github.com/driftyco/ionic-app-lib/blob/master/lib/setup.js#L71

I think these watch patterns should be set from `ionic.project`.

@mhartington could you please take a look at this?

```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.8
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: 1.6.2 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.4 Build version 6E35b 

```

**Comment by jbavari** [comment]
@softBarbarian Thanks for your input on this.

I know this is an important feature. The reason it hasn't been integrated into mainstream is that many developers may venture off the set 'conventions' of ionic. The reason most developers (right now) rolled their own due to the differing layouts of how users may have their files laid out. Some might even prefer to use Gulp.

Regardless, I've had my hands tied up working on another project. However, that project also heavily ties into this as well and I will be integrating common build tactics (uglification, concat, updating html, etc). 

I'm planning on having an interface to select the file locations (choose html, css, js, etc) and then have those files being used in the project build steps.

> After some investigantion I determined that there are hard coded sass patterns that point to www folder in https://github.com/driftyco/ionic-app-lib/blob/master/lib/setup.js#L71

Regarding the setup.js file - that sets the initial watch patterns for sass recompilation, but only if the ionic.project file does not have them once users run `ionic setup`.

Speaking of, there are other places that 'www' folder is hard coded. 

I'm working on it. Bear with me.

**Comment by jbavari** [comment]
@softBarbarian Focusing on this right now.

I've got an app with my `documentRoot` set to `app` - wherein all my html/css/js files are at.

When I set up the ionic.project file like you did, ran `ionic serve`, I got the issue:

```
[gulp-sass] file to import not found or unreadable: www/lib/ionic/scss/ionic
Current dir: /Users/JoshBavari/Development/testing/s2/scss/ on line 22 in /Users/JoshBavari/Development/testing/s2/scss/ionic.app.scss
```

Which appears to be the same error you had.

I then looked at my scss/ionic.app.scss file - and changed:

``` scss
@import "www/lib/ionic/scss/ionic";
```

to:
``` scss
@import "app/lib/ionic/scss/ionic";
```

Then my sass compilation went through perfectly.

Can you try that and see if it solves the issue?

**Comment by softBarbarian** [comment]
@jbavari thanks for taking a look! Yes it indeed fixes the issue. I should have caught that...
Also @jbavari I am pretty exited that you are working on your `other project` that is related to this issue. is it a long awaited `ionic-build-release` feature? there have been a lot of discussions about it:
#168 
#143 
#16 
#270 

Can you please give us a little sneak peak of upcoming feature? is it going to be updated gulp script or ionic cli command ?
Thanks in advance.

**Comment by jbavari** [comment]
@softBarbarian The cat is out of the bag - the other project has been Ionic Lab.

What I'm working on now is a build release feature - you are correct. 

I'm going through those issues right now - trying to come up with the best way that will work with release features for all users.

Right now - I'm leaning more towards having it being an integrated CLI command - to get around updating and maintaining users gulpfiles (they might change them, and we dont want to over write their gulpfiles between releases).

When you do your release builds - do you start with 'app' folder and then compile/minimize to another folder? Or do you minimize in line?

**Comment by softBarbarian** [comment]
It is really great that you are finally working on it!

@jbavari i start at `app` folder and then compile/min/uglif to `www` folder just because i did not have time/knowledge to minimize inline. Also if one minifies inline the code that one is working on will be minified so to resume working you need to unminify it.

Here is roughly how i did it in my project.
if `ionic build dev` -> just copy source from app to www and
if  `ionic serve` -> serve from app folder
if `ionic build release` -> copy from `app` to `www` + min/uglify html, css, js

**Comment by softBarbarian** [comment]
@jbavari hey just checked out Ionic Lab ---  AWSOME!!!!!

**Comment by jbavari** [comment]
Take a peek at [this branch, release.js](https://github.com/driftyco/ionic-app-lib/blob/minify/lib/release.js).

I'm using usemin in app-lib, parsing HTML for compilation, then minify, postprocess, and remove end results from ios/android www paths.

What do you think of it?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
