### ISSUE TITLE
"ERROR: Failed to launch application on device" & "Error: Failed to install application on device"

### ISSUE THREAD

**Issue by GopalakrishnanK** [driftyco/ionic-cli#538]
Hi,

when i run 'ionic run android' cmd i get the error as in the tilte. i've spend half a day and tried so many steps but i can't find whats the problem. can anyone help me with this.....?

![capture](https://cloud.githubusercontent.com/assets/10287362/8931575/f21a8bc4-3554-11e5-8c19-9dd99d475f7c.PNG)

**Comment by secret4info** [comment]
do you have device attached with Computer and checked it if it is available to command or not and is it running android os or something else.

**Comment by GopalakrishnanK** [comment]
yes i've attached my android device with my computer.................... i've enabled USB Debugging also.....

**Comment by adamdbradley** [comment]
Greetings @GopalakrishnanK!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by GopalakrishnanK** [comment]
Thanks @adamdbradley! 
Let me tell you my fix for this error. The actual problem is my device drivers are not installed properly in windows7. So I've installed drivers manually and it worked.
