### ISSUE TITLE
Ionic resources --splash and XXXHDPI

### ISSUE THREAD

**Issue by pmmenneg** [driftyco/ionic-cli#540]
HI there. The splash screens generated by `ionic resources --splash` include an XXXHDPI version with generated dimensions of 1280px x 1920px, even when feeding the generator a baseline image of 2650px x 2560px. 

Issues:

1) Given supplying a 2560px x 2560px source image, shouldn't the resulting XXHDPI image be large enough that it doesn't need to be scaled up (as with the current 1280px x 1920px one)?

2) For the XXXHDPI devices (Samsung S6, Nexus 6), with screen sizes of 1440px x 2560px, the resulting 1280x1920 image is stretched due to the different aspect ratios. Are there adjustments that can be made to send back the 'correct' aspect ratio, or is this a simple reality of Android given that other future XXXHDPI devices will have different aspect ratios.

**Comment by adamdbradley** [comment]
Greetings @pmmenneg!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
