### ISSUE TITLE
cordova plattform add windows >> error: \npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23

### ISSUE THREAD

**Issue by HansS** [driftyco/ionic-cli#548]
os: win 8.1 64bit
node: 012.7
cordova:5.1.1

**Comment by adamdbradley** [comment]
Greetings @HansS!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
