### ISSUE TITLE
bug: `$ ionic add *` doesn't add to www/lib

### ISSUE THREAD

**Issue by jimmyhsu** [driftyco/ionic-cli#555]
Type: bug

Platform: all

I'm running into an issue where this function is creating a `bower_components` folder instead of adding the bower package to `www/lib` as before. I'm pretty certain this is a bug, but I'm not sure why this issue suddenly cropped up after running `$ npm install -g ionic`.

For now I just manually copy the files from the `bower_components` folder to my `www/lib` folder, but it's something that should be addressed. If someone can point me as to where I can help fix this, that would be awesome as well.

This is the result of running `$ ionic info`:
```
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 4.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b
```

If anymore information is need let me know.

**Comment by adamdbradley** [comment]
Greetings @jimmyhsu!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by jimmyhsu** [comment]
Just for legacy, I had figured this out.

Just check to make sure you have a `.bowerrc` in your root folder (same as your `bower.json`) :smiley: 
Inside it should be:
```
{
  "directory": "www/lib"
}
```
