### ISSUE TITLE
Accessing livereload from device when running ionic run android inside a docker container

### ISSUE THREAD

**Issue by lewisl9029** [driftyco/ionic-cli#557]
I have ionic-cli set up inside a docker container inside a vagrant vm, and would like to try out `ionic run android --livereload`.

I managed to get usb pass-through working for the docker container and vm. But I'm getting blocked because the ip address inside the docker container (172.17.0.1) is different from my machine's physical address (192.168.1.11), so the app on the device ends up trying to reach 172.17.0.1 from the outside and fails.

I think an adequate solution would be adding a new option to specify an address for the device to connect to (`--external-address x.x.x.x`, maybe?), that's separate from the address used to serve the app. Would you guys accept a pull request for something like this?

**Comment by AgDude** [comment]
This can also be accomplished using a "public_network" for vagrant (assuming you are on a LAN that will let you do this). This will create a second network adapter on the vagrant machine, and ionic run will give you the option of which adapter to use.

**Comment by lewisl9029** [comment]
I looked into the public_network option for vagrant but I was a bit intimidated by the security warnings on the vagrant docs page. I'd rather not have to open that can of worms if there's a workable alternative like the one proposed in my PR.

**Comment by adamdbradley** [comment]
Greetings @lewisl9029!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
