### ISSUE TITLE
ionic state reset changes package.json

### ISSUE THREAD

**Issue by Freundschaft** [driftyco/ionic-cli#564]
I have this:

"cordovaPlugins": [
    "ionic-plugin-keyboard",
    "cordova-plugin-statusbar",
    "cordova-plugin-camera",
    "./engine/cordova-crosswalk-engine-c0.6.2",
    "uk.co.workingedge.phonegap.plugin.launchnavigator",
    "https://github.com/danwilson/google-analytics-plugin.git",
    "cordova-plugin-file-transfer",
    "cordova-plugin-whitelist",
    "cordova-plugin-inappbrowser",
    {
      "locator": "https://github.com/carlosjavier84/phonegap-facebook-plugin.git",
      "id": "com.phonegap.plugins.facebookconnect",
      "variables": {
        "APP_ID": "234234234234",
        "APP_NAME": "testapp"
      }
    }
  ],

and when I run ionic state reset, there is always an additional https://github.com/carlosjavier84/phonegap-facebook-plugin.git entry that gets appended to cordovaplugins

I think this is a bug because then the plugin gets installed twice :(

**Comment by Freundschaft** [comment]
okay it seems that cordova plugin save shows the same behavior

**Comment by Freundschaft** [comment]
maybe this line that needs to be changed?

https://github.com/driftyco/ionic-cli/blob/4da736396f7c1a23b15716c62839ba5f411b4d8e/lib/hooks/after_plugin_add/010_register_plugin.js#L45

**Comment by Freundschaft** [comment]
I think its required to compare locator as well, right?

**Comment by jbavari** [comment]
I'll look into this today. Thank you for reporting.

**Comment by jakub-g** [comment]
The same happens to us with `ionic state restore`

Basically AFAIU there's a fundamental mismatch between the ionic way and cordova way of handling the variables

When you have in `package.json` in `cordovaPlugins`:

    {
      "variables": {
        "APP_ID": "123123",
        "APP_NAME": "test"
      },
      "locator": "cordova-plugin-facebook4@1.6.3",
      "id": "cordova-plugin-facebook4@1.6.3"
    },
    
then when you do `ionic state restore`, ionic prints and executes the following command
    
    cordova plugin add cordova-plugin-facebook4@1.6.3 --variable APP_ID="123123" --variable APP_NAME="test" 

which adds the following entry to `package.json` (plain plugin name without variables)

    "cordova-plugin-facebook4@1.6.3",
 
so now you have two entries for such plugin, one plain `plugin@version` and the other as JSON object.
    
You can have cordova save the variables but then you have to pass `--save` to the `cordova plugin add ...` command, and the variables will be saved not in `package.json` but in `config.xml` like this

    <plugin name="cordova-plugin-facebook4" spec="~1.6.3">
        <variable name="APP_ID" value="123132" />
        <variable name="APP_NAME" value="test" />
    </plugin>

(which is a pain BTW because cordova and ionic use a different XML formatter) and in `package.json` you will still end up with just a "plain" entry `"cordova-plugin-facebook4@1.6.3"`

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
