### ISSUE TITLE
Why does `ionic io init` modify ionic-core.js?

### ISSUE THREAD

**Issue by angusfretwell** [driftyco/ionic-cli#567]
`ionic-service-core` is installed to www/lib/ via bower, so why does running `ionic io init` modify the file, rather than utilizing the credentials in `.io-config.json` somehow?

**Comment by adamdbradley** [comment]
Greetings @angusfretwell!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
