### ISSUE TITLE
ionic serve error

### ISSUE THREAD

**Issue by andresetevejob** [driftyco/ionic-cli#579]
Hi All, I have same bug how do you do to solve this

**Comment by jbavari** [comment]
Unless you provide more information about the bug you are having, we cannot help you solve it.

**Comment by adamdbradley** [comment]
Greetings @andresetevejob!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
