### ISSUE TITLE
Occasionly `ionic state reset` results in an empty `platforms/ios` directory

### ISSUE THREAD

**Issue by Deminetix** [driftyco/ionic-cli#585]
As the title says. We are unable to use the CLI in a continuous integration server because 1 in ~7 builds ends up with the an empty platform directory. Unfortunately there are no errors displayed and i can't see in the code how this could happen.

Maybe you guys might have a better idea? :)

**Comment by adamdbradley** [comment]
Greetings @Deminetix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
