### ISSUE TITLE
ionic state restore not pulling latest version of plugins

### ISSUE THREAD

**Issue by ravishtiwari** [driftyco/ionic-cli#589]
Hi, 
It seems that doing __ionic state restore__ does not pull latest version of a plugin.
I recently ran into some trouble Local Notification plugin (https://github.com/katzer/cordova-plugin-local-notifications) and my app was crashing trying to add local notification on iPhone (with iOS 9.1 Beta).

In order to reproduce the problem from dev machine and identify if problem was related to my code or cordova ios platform, and I've all required plugins available locally, I did following:
 **_ionic state restore_**
Looking at plugins Git repo, I found that @katzer already fixed the iOS issue on Sept 2, but, I was still facing the same problem even after _state restore_ and fix was not there in plugin source locally.

I was only able to resolve the problem after doing a fresh install of plugin by doing:
* _cordova plugin rm de.appplant.cordova.plugin.local-notification_
* _cordova plugin add de.appplant.cordova.plugin.local-notification_
Why ionic state restore is not pulling latest version of a plugin? I mean we did not tag a commit version in __package.json__ when add a plugin, so, when we do restore it should pull the latest version.

**Comment by adamdbradley** [comment]
Greetings @ravishtiwari!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
