### ISSUE TITLE
Browser add crosswalk does not works

### ISSUE THREAD

**Issue by calebeaires** [driftyco/ionic-cli#595]
When I compile APK using ionic-cli with Crosswalk Lite, the size is so big as default Crosswalk. Do both has the same size or IONIC CLI browser function are not doing its job and why Lite version is listed on ionic browser add crosswalk?

**Comment by adamdbradley** [comment]
Greetings @calebeaires!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
