### ISSUE TITLE
Adding plugin from URL doesn't update package.json

### ISSUE THREAD

**Issue by dgobaud** [driftyco/ionic-cli#601]
#359 should be reopened. I'm still seeing the problem in 1.6.5.

**Comment by Ionitron** [comment]
Greetings @dgobaud!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by imsheth** [comment]
Issue still persists !
