### ISSUE TITLE
Use "table" package instead of "cli-table"

### ISSUE THREAD

**Issue by gajus** [driftyco/ionic-cli#603]
https://github.com/gajus/table package is a very modular, well documented and well tested module/function for generating text tables. It allows granular customisation of how table contents is aligned, text wrapping, text truncation, border style and text padding.

If accepted, I will happily create a PR.

**Comment by Ionitron** [comment]
Greetings @gajus!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
