### ISSUE TITLE
deploy messages die partway through deploy

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ionic-cli#606]
If I do:

```
ionic run ios --device
```

It compiles the app file and starts the deployment, but it dies at about [30 %] and gives me my console back. It clearly is still running in the background because a few seconds later the app opens on my phone.

If I replace `ionic` with `cordova` it works.

**Comment by Ionitron** [comment]
Greetings @ptarjan!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
