### ISSUE TITLE
Ionic serve is not working on a freshly generated project

### ISSUE THREAD

**Issue by ospfranco** [driftyco/ionic-cli#607]
Hello, I created a sample project, using:

Cordova CLI: 5.3.3
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v4.1.2
Xcode version: Xcode 7.0.1 Build version 7A1001

however live reload doesn't seem to work:

ionic $ HTML changed: www/index.html
Unable to update live reload: { [Error: socket hang up] code: 'ECONNRESET' }

Tried running ionic address and change to localhost, then I got a different error:
ionic $ HTML changed: www/index.html
Unable to update live reload: { [Error: write EPIPE]

Any ideas?

**Comment by Ionitron** [comment]
Greetings @ospfranco!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
