### ISSUE TITLE
Is "gulpDependentTasks" option in ionic.project working?

### ISSUE THREAD

**Issue by tamakisquare** [driftyco/ionic-cli#610]
According to the doc:
> gulpDependentTasks - gulp tasks that are run before ionic serve launches

I tried putting a gulp task, that prepares for the dev build, into the array but nothing happened. I tried googling "gulpDependentTasks" but didn't find any articles, besides the official doc, mentioning about it.

How is `gulpDependentTasks` supposed to function?

**Comment by yuitakano** [comment]
I have the same problem.

**Comment by guiguidu31300** [comment]
I have the same problem too.

**Comment by jbavari** [comment]
I see what happened, and I'm working on it. The name for the tasks was named wrong in the refactor.I'm patching it now.

**Comment by jbavari** [comment]
@tamakisquare I've found what happened.

The feature first came to us as a [pull request](https://github.com/driftyco/ionic-app-lib/pull/17) back in August 5th.

It turns out, it follows the Britist spelling of `gulpDependantTasks`, and the documentation follows American english spelling of `gulpDependentTasks`.

For now, you can use `gulpDependantTasks` until we change the spelling in the code. I'll go ahead and update the `ionic.project` README information to use the correct spelling.

**Comment by tamakisquare** [comment]
@jbavari - Works like a charm! Thanks for figuring out the problem for us. No wonder I couldn't get any results when searching for `gulpDependentTasks` in the source code. That tiny a/e culprit.
