### ISSUE TITLE
Creating a project exception error: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by DynalabsPT** [driftyco/ionic-cli#611]
I was trying to create a new project and I got an error. 
Here are the details:
iopo0166:Apps martasegadaes$ ionic start Cards blank
Creating Ionic app in folder /Users/martasegadaes/Desktop/Projects/Apps/Cards based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project
Adding in iOS application by default
An uncaught exception occurred and has been reported to Ionic
Cannot read property 'hasOwnProperty' of undefined (CLI v1.6.5)

Your system information:
Cordova CLI: 5.3.3
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.12.5
Xcode version: Xcode 7.0.1 Build version 7A1001

**Comment by Ionitron** [comment]
Greetings @DynalabsPT!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
