### ISSUE TITLE
On a slow network "ionic upload" claims success but IonicDeploy download gets 404 from S3 AWS

### ISSUE THREAD

**Issue by odinixadmin** [driftyco/ionic-cli#617]
Whenever ionic upload takes a long time (say on slow network) to complete the upload process, app fails to download that update. The failure to download occurs in the following location of the IonicDeploy.java file with a 404 error:

        // expect HTTP 200 OK, so we don't mistakenly save error report
        // instead of the file
        if (connection.getResponseCode() != HttpURLConnection.HTTP_OK) {
          return "Server returned HTTP " + connection.getResponseCode()
              + " " + connection.getResponseMessage();
        }

IonicDeploy update downloader is not at fault (except it doesn't report the proper error to the client and remains silent), but the real issue is that AWS S3 URL does not exist (404). If I try to open the URL in the browser I get:

```
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
```
My guess is "ionic update" is incorrectly returning success even when AWS S3 file is not saved successfully.

**Comment by Ionitron** [comment]
Greetings @odinixadmin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
