### ISSUE TITLE
Can't install ionic package on windows 

### ISSUE THREAD

**Issue by ufhy** [driftyco/ionic-cli#621]
this is version:
``` 
node -v
4.2.1

npm -v 
3.3.8

cordova -v
5.3.3
```

I was run as administrator this command:
```
npm install -g ionic
```

I get error:
```
npm ERR! fetch failed https://registry.npmjs.org/finalhandler/-/finalhandler-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=sock
et hang up
.
.
.
npm ERR! fetch failed https://registry.npmjs.org/npm/-/npm-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=sock
et hang up
```

**Comment by Ionitron** [comment]
Greetings @ufhy!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
