### ISSUE TITLE
before_serve and before_prepare dont work

### ISSUE THREAD

**Issue by MarkySparky** [driftyco/ionic-cli#676]
Even though the readme in the ./hooks folder says that these hooks should work, they don't.

I've tried ionic_cli 1.7.11 and 2.0.0 release candidate

Anything I put in the ./hooks/before_serve or .hooks/before_prepare folders dont get executed.

If I run cordova serve, both hooks get executed.

Permissjons are fine. Same hooks moved to after_prepare works fine

Looks like ionic is just ignoring these before hooks - looks like an oversight.

after_serve also doesnt work.

Id like to use these hooks to set up a test server and add some angular modules depending on the parameters passed. i.e. ionic server development or ionic serve production

I can do this with gulp of course, but id lke to use the documented ionic way and use hooks instead (which works if I use cordova instead)

**Comment by jarodms6** [comment]
+1

**Comment by danvirsen** [comment]
+1

**Comment by jdat82** [comment]
My guess is that ionic is not relying at all on cordova concering the serve command. For all others commands like emulate or run they dispatch to cordova, so cordova hooks are called. But I presume that `ionic serve` and `cordova serve` are too different things, so, cordova hooks are not called. Not sure there is a solution.

**Comment by luiscvalmeida** [comment]
+1

**Comment by marcochavezf** [comment]
+1

**Comment by axelingadi** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by jaufgang** [comment]
This issue does not appear to be resolved.  I am using  CLI version 2.2.1 and am experiencing the same problem. 
`before_serve` and `after_serve` hooks do not get run at all.

**Comment by jthoms1** [comment]
@jaufgang The comment by @jdat82 speaks to this. We are not using cordova serve so the cordova hooks will never get executed.

**Comment by jaufgang** [comment]
@jthoms1, @jdat82 's comment is a guess at what the underlying cause of the problem may be, not a definitive statement and not a solution. 

I would expect that the problem could be resolved by modifying the `ionic serve` script to call the expected hooks where appropriate to mimic the behaviour of `cordova serve`.  If not, the difference should be clearly documented.

The Ionic 2 starter project created by the CLI command `ionic start myapp`  includes a [hooks/Readme.md](https://github.com/driftyco/ionic2-app-base/blob/master/hooks/README.md) file that lists `before_serve` and `after_serve` as available hooks.  If these hooks are not supported by ionic, then that should be made clear.

This may be tangential to this issuse, but while I am mentioning that `hooks/Readme.md` file I would also like to point out that it should be updated to reflect the facts that:

- The `/hooks` folder has been deprecated by Cordova, and that the `<hook>` tag in config.xml is now the recommended way to add hooks
- The `module.exports = function(context) {}` syntax recommended by that readme _only_ works when used with the `<hook>` tag and _not_ with scripts in the `/hooks` folder 

I found this information in the [Cordova Hooks Guide](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/)

This is consequential.  As an Ionic developer looking into using hooks for the first time, I have wasted a fair bit of time trying to make sense of behaviour that appears buggy  due to misinformation in the `hooks/Readme.md` file.

**Comment by jdat82** [comment]
@jaufgang I understand your frustration and most people encounter that kind of thing from time to time on open source projects but you should remember that this is a HUGE project with a SMALL team. So this kind of thing will keep happening. There is a strong possibility that your advice will just stay an advice in this issue. The best you could do to really make a difference and in the process help the community is provide a pull request that modify `hooks/Readme.md` directly. In the mean time thanks for clarifying things in this issue, it will help people finding it.

**Comment by vegardlarsen** [comment]
This is still an issue with ionic-cli v3.19.0.

**Comment by dwieeb** [comment]
@vegardlarsen Can you elaborate? The `hooks/` directory was removed from our starters. Here are the docs for Cordova hooks: https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/

**Comment by vegardlarsen** [comment]
@dwieeb Since this was 20 days ago, and I didn't note down exactly what I was experiencing, it appears I have forgotten the exact steps I took.

To test this, I tried generating a new app, and defining a hook using the config file instead. First I added two script files:

```
// prepare.js and error.js with different output
console.error("prepare");
```

Then I added the following lines to my `config.xml`:

```xml
    <hook src="serve.js" type="before_serve" />
    <hook src="prepare.js" type="before_prepare" />
```

Running `ionic serve` should, as far as I can tell, output an error message, which it does not.  So should `ionic cordova prepare` but nothing happens then either. (Yes, I added a platform)

```
cli packages: (C:\Users\vegar\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v9.3.0
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\users\vegar\android

Misc:

    backend : pro
```

**Comment by LRonHubs** [comment]
Why is this closed.

**Comment by LRonHubs** [comment]
I feel like ionic is broken.

**Comment by LRonHubs** [comment]
It's impossible to do anything without running into 1,000 errors in things that are described as features.
