### ISSUE TITLE
ionic 1.7.12 undefined live reload

### ISSUE THREAD

**Issue by gaurav-chandra** [driftyco/ionic-cli#718]
```
Running live reload server: undefined
```
get the above when I try to run
```
ionic serve --lab
```
on 1.7.12

**Comment by mhartington** [comment]
I'm seeing this as well, but it's not preventing live-reload from working for me. Does live-reload work for you?

**Comment by emilyemorehouse** [comment]
I'm seeing this and it is breaking live-reload for me. Also on 1.7.12 for the CLI.

**Comment by thetwosents** [comment]
Can confirm live-reload not working after full reinstall and empty of cache

**Comment by mhartington** [comment]
Alright, thanks yall.

@tlancina should be able to take a look at this

**Comment by emilyemorehouse** [comment]
I've noticed that live reload works for me when viewing with Ionic Lab (though my live reload server still shows as undefined), but live reload doesn't work when viewing directly.

**Comment by rhalff** [comment]
The `undefined` seems to be caused by this commit: 
https://github.com/driftyco/ionic-app-lib/commit/79dfc4cd7865b882a591e9a14e559b55da58fbd2#diff-3288939317efd62bfc509440d662caca

runLiveReload() sets `options.liveReloadServer`:
https://github.com/driftyco/ionic-app-lib/blob/79dfc4cd7865b882a591e9a14e559b55da58fbd2/lib/serve.js#L313

Because of the re-arrangement the option is not yet set.

If the logging is moved down like so:

```javascript
    .then(function(server) {
      if (options.useProxy) {
        return Serve.setupProxy(options, app);
      }
    })
    .then(function() {
      return Serve.runLivereload(options, app);
    })
    .then(function(data) {
      logging.logger.info('Running live reload server:'.green.bold, options.liveReloadServer);
      logging.logger.info('Watching:'.green.bold, options.watchPatterns);
      return Serve.startServer(options, app);
    })
```

the url will be shown correctly.

I wanted to make a pull request, but then also notice `(server)` and `(data)` are never used.
Which leads me think linting is not done, which is the case and I'm hesitant to just remove `server` and `data`.

**Comment by xl-y** [comment]
I have the same problem. The ionic version on my PC is 1.7.14.Even though it throw this kind of error,it still works well for me.

**Comment by tlancina** [comment]
@rhalff thanks for looking into this, the PR is much appreciated! It should come out in the next release.  

Although to be clear to anyone who comes to this issue, the `undefined` is purely cosmetic, if livereload isn't working I would suggest making sure your `watchPatterns` are correct.  And of course please file an issue if you believe there's a bug, thanks!

**Comment by maximsko** [comment]
I don't know if this is the reason for it, but my livereload doesn't work as well on `ionic serve`, also showing me "Running live reload server: undefined"
My watchPatterns seem to be set correctly as well.

**Comment by rhalff** [comment]
If Livereload does not work, also try to install crosswalk:

http://ionicframework.com/docs/cli/browsers.html

If your android version is a bit older websockets do not work. (If I remember correctly)

@maximsko I guess the next release is not out yet, so it does not yet include the patch.
