### ISSUE TITLE
After V2 installation can't build android app on windows

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#757]
_From @szuzul on January 31, 2016 22:16_

Type: Bug
Platform: Windows

After ionic v2 installation I'm getting strange behavior if  I enter ionic build or ionic run.
I don't have ios platform In my package.json
ionic run
 You're trying to build for ios, but don't have the platform installed yet.
? Installing ios for you.

_Copied from original issue: driftyco/ionic#5273_

**Comment by adamdbradley** [comment]
_From @brandyscarney on February 1, 2016 18:28_

Can you run `ionic info` and paste the output, please?

**Comment by JT-Bruch** [comment]
I got the same errors...

Screenshot #1:
![image](https://cloud.githubusercontent.com/assets/7430562/13128641/e27047e8-d59c-11e5-8b2d-620a8305bfe5.png)

Screenshot #2:
![image](https://cloud.githubusercontent.com/assets/7430562/13128652/f4a09d6e-d59c-11e5-8bf1-b5fdf05ccc70.png)

**Comment by brandyscarney** [comment]
@JT-Bruch You can't use `ionic run ios` on a Windows machine, it requires a Mac. 

https://forum.ionicframework.com/t/ionic-build-ios-not-working-in-windows/38750

**Comment by jgw96** [comment]
Hello all! Brandy is correct, an OSX machine is required for ios development at this time. Thanks for using Ionic!

**Comment by jgw96** [comment]
reopening this as the original issue was related to Android

**Comment by thardes2** [comment]
I still have the issue here - I am following the guide [here](http://ionicframework.com/docs/v2/getting-started/installation/), but I get errors:

`ionic platform add android
(node:7992) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Error: Platform android already added.
Caught exception:
 undefined
`

and afterwards:

> $ ionic run android
(node:9068) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> Running 'run:before' gulp task before run
[14:06:21] Starting 'clean'...
[14:06:21] Finished 'clean' after 35 ms
[14:06:21] Starting 'build'...
[14:06:21] Starting 'sass'...
[14:06:21] Starting 'html'...
[14:06:21] Starting 'fonts'...
[14:06:21] Starting 'scripts'...
[14:06:21] Finished 'html' after 54 ms
[14:06:21] Finished 'scripts' after 106 ms
[14:06:21] Finished 'fonts' after 112 ms
[14:06:21] Finished 'sass' after 901 ms
[14:06:27] Finished 'build' after 6.58 s
[14:06:27] Starting 'run:before'...
[14:06:27] Finished 'run:before' after 2.77 μs

> • You're trying to build for androidbut don't have the platform installed yet.
∆ Installing android for you.
Installing cordova-plugin-device
Installing cordova-plugin-console
Installing cordova-plugin-whitelist
Installing cordova-plugin-splashscreen
Installing cordova-plugin-statusbar
Installing ionic-plugin-keyboard
Caught exception:
 Error: Command failed: cordova plugin add --save cordova-plugin-console
C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:126
                    throw e;

> $ ionic info

> Your system information:

> Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v6.2.2


I am posting it here, as I followed the tutorial step by step.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by neuberfran** [comment]
Please help me

![image](https://cloud.githubusercontent.com/assets/7308528/20613754/cfdf97c8-b2a5-11e6-81dd-f755e6560e35.png)
