### ISSUE TITLE
Ionic V2 generator: parent directory 

### ISSUE THREAD

**Issue by cmellinas** [driftyco/ionic-cli#764]
The generator of pages is a very interesting tool for this V2 version. 

I understand the concept of 'Page' but how do you see future big projects architectures with lot of specific modules and pages (nesting could become interesting for master/details pattern or to group inside specific module)

We could imagine something like that:
ionic g page myPage --parent page1 (a parent flag could allow to handle all types of architectures Ionic devs want)

**Comment by tlancina** [comment]
It's an interesting question, as right now generators don't allow that much flexibility.  That being said, because each component is modular, it's pretty trivial to generate a page and then move it to wherever you need.

I believe [angular-cli](https://github.com/angular/angular-cli) has blueprints similar to ember-cli, which would allow more customization at the cost of a little added complexity. How the angular-cli and Ionic will interact is still something we need to look into.

For the time being, there are no plans to add flags or added customization to keep things simple, but that may change going forward.

**Comment by cmellinas** [comment]
Great ! 
Yea, it's not a blocking feature, I was just wondering if it was hard to implement with your cli 
Let me know if one day, you had such customization :)

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
