### ISSUE TITLE
Older version of ionic2 project doesn't build

### ISSUE THREAD

**Issue by nitecloack** [driftyco/ionic-cli#885]
Hi 

An older version of ionic2 project using typescript running at package beta Angular2: 2.0.0-beta.0 Ionic-Framework: "2.0.0-alpha.48" from package.json. 

CLI: 2.0.0-beta.23
Ionic Version: 2.0.0-beta.3

When running "ionic serve" updates does not reflect to the www/build.
How do I update the project to latest?

PS: im new at Ionic and stuff 

Many Thanks

**Comment by jkeczan** [comment]
This is because they transitioned to gulp as of cli beta.21 I believe. You will need to update your project to allow for the new build build process. 

https://forum.ionicframework.com/t/attention-upcoming-ionic-2-starter-changes/45058/25

Here is a link to the announced changes. They do not have an official migration pattern so it is up to us to determine the path forward. I am currently going through this process now.

**Comment by tlancina** [comment]
@nitecloack @jkeczan do you have an ionic.config.js file? The CLI should prompt you to download the gulpfile needed for building when running serve with ionic.config.js in your project root.

**Comment by nitecloack** [comment]
I'll have a look at that.

**Comment by tlancina** [comment]
Hey all, I'm going to close this and point people to: https://forum.ionicframework.com/t/ionic-2-projects-updating-to-beta-4/49054/1 for steps on updating.
