### ISSUE TITLE
new live reload ignores cross domain policy (CORS)

### ISSUE THREAD

**Issue by konsultaner** [driftyco/ionic-cli#89]
For some reason the content loaded by serve using the new live reload feature does not allow cross  origin resource sharing(CORS). So it ignores the cross domain policy set inside the config.xml

**Comment by academo** [comment]
This is still a problem in the current ionic cli (1.3.10), this issue should not be closed.

**Comment by filipesilva** [comment]
Although this is not a fix per se, the workaround can be found in https://github.com/driftyco/ionic-cli#testing-in-a-browser, subsection Service Proxies. 

It's not perfect (you still need to change code from 'local' urls to real environment urls) but I haven't found any better alternative so far.

**Comment by mattezell** [comment]
I agree that this likely shouldn't be closed, or at least closed without a bit more info... A quick Google or two shows that this is an often shared sticking point for Ionic developers...  It's very easy to find a lot of discussions where people are having CORS related issues when using "ionic run -l", yet it's very difficult/impossible to find an official solution... 

For me, developing my API local to the same machine that I am using live reload and debugging via adb on, I am unable to find a working workaround... I've yet to find a magical combination of proxy settings and Windows host file entries that will get around CORS issues... Additionally, overriding $http defaults, as suggested elsewhere has proven similarly ineffective in working around this.

Were we imagining things?  Is this how live reload has been from the start, or was it previously 'just working' without CORS issues as many seem to believe?  

Is there a simple and official way to configure a project so that CORS issues don't arise when using 'run -l' on the same development server as the API is running?

**Comment by josephfinlayson** [comment]
Same problems for a salesforce integration:

     [Error] Failed to load resource: Origin http://10.1.1.171:8100 is not allowed by Access-Control-Allow-            Origin. (describe, line 0)
     [Error] XMLHttpRequest cannot load   https:/asdf.cs18.my.salesforce.com/services/data/v29.0/sobjects/App_Settings__c/describe/?_=1424263174184. 
     Origin http://10.1.1.171:8100 is not allowed by Access-Control-Allow-Origin. (10.1.1.171, line 0)

http://10.1.1.171 is my local IP

**Comment by kwoxford** [comment]
Same problem with iOS 8 and OSX Yosemite, with everything up to date including all dependencies - <code>run</code> works but <code>run -l</code> hits CORS problems. Ditto <code>emulate</code>.

**Comment by tobbbe** [comment]
Here's a workaroud I use: https://gist.github.com/tobbbe/3fd51f9537e645c73fb9

**Comment by kwoxford** [comment]
Thanks, but <code>run -l</code> takes place on a real device so I don't see how Chrome enters into it (I have Safari set in the same way, anyway). The CORS issue is between the ionic server and iOS, somehow.

**Comment by josephfinlayson** [comment]
Is there a way of triggering the respective webview to ignore CORS policies?

Joseph Finlayson

+44 796 796 5870
+49 162 395 0220

**Comment by evanmrose** [comment]
Bumping this, working on a project and serve works fine but emulate dies with cors issues

**Comment by kwoxford** [comment]
Yes, just adding -l to the emulate command kills it. Note that this isn't a matter of CORS with external urls, it kills internal urls so the emulated app can't access its own assets with $http.

**Comment by cnd5041** [comment]
I think this issue is causing my 'Unexpected connection failure' with Azure Mobile Services as well in case somebody runs into that. 
Was there a workaround for running on the device? It looked like the one workaround was for browsers and the proxy workaround was for -serve..

**Comment by Yonn-Trimoreau** [comment]
Still a huge problem for testing on physical android. I'm trying to proxy my server into livereload so the web app will think all responses are coming from the same server.. I'd like to have ionic.project's specs, are there any ?

**Comment by mattezell** [comment]
Thanks for breaking this down using crayon typeset for me @Yonn-Trimoreau :)  This is definitely the easiest workaround presented thus far.. I know it's not a 'new' one, as it's been documented, but for some reason my previous attempts to use this approach had failed.. Up and running against my test APIs without issue now!  Thanks again!

**Comment by mably** [comment]
@kwoxford have you found a solution to your local assets access with livereload activated?  we are hit by the same problem :(

**Comment by jeremy-dobler** [comment]
This issue greatly affects my app as well. Our production environment utilizes a universal login call but that returns a specific rest url for that customer to utilize. I cannot use the proxy as suggested in https://forum.ionicframework.com/t/proxy-problems-with-ionic/43354. Specifically because my proxy array would have to end up looking something like

```
proxies: [
  {
    path: "/login",
    proxyUrl: "http://the-universal-login"
  },
  {
    path: "/api1",
    proxyUrl: "http://rest1"
  },
  {
    path: "/api2",
    proxyUrl: "http://rest2"
  },
  {
    path: "/api3",
    proxyUrl: "http://rest-west"
  },
  {
    path: "/apidev",
    proxyUrl: "this url can be injected by the build process to support all our dev environments"
  }
]
```
my login call would have to look like
```
http.get('/login').subscribe((resp) => {
  //resp.restUrl = http://dataCenterRestUrl/corporationToken/
  // dataCenterRestUrl can take the form of any of the following formats (http://dev-backend/1sd/, http://rest1/1sd/, http://rest-west/1sd/)
  this.DataCenter = // parse resp.restUrl to determine what "api" endpoint to now hit
  this.token = //parse resp.restUrl to get the corporationToken
  //currently we just say this.restUrl = resp.restUrl which is clean and easy to read
});
```
and then every single http call would have to look something like this
`http.get('/api${DataCenter}/${tokenForCorporation}/restOfUrlPath')`
compared to our current implementation of
`http.get('${restUrl}/restOfUrlPath')`
IMO, having to implement code like this to support the proxies fix suggestion is hacky, wrong and defeats the purpose of that proxy config. It also defeats the purpose of our universal login as we add new datacenters often and would have to update this config to support these new datacenters whenever they are added.

At our company, we have decided that this is extremely hacky and hard to read so we are not implementing a fix like this. We have just decided to not use the `ionic run -l` command.

It should be noted that when running locally in a development environment, we use a hostfile hack to ignore the cors issue
