### ISSUE TITLE
Not running build tasks after update Ionic

### ISSUE THREAD

**Issue by kevinnascimento** [driftyco/ionic-cli#940]
After upgrading the version of the Ionic beta, you are not running the build tasks.

![image](https://cloud.githubusercontent.com/assets/5147127/14626356/009c23fa-05c1-11e6-9d76-765a66818a73.png)

I am using TypeScript.

Your system information:

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.7.0
ios-sim version: 5.0.1
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175

**Comment by iignatov** [comment]
@kevinnascimento I guess that the problem might be caused by the fact that you're using the latest **Ionic CLI** but too old version of the **Ionic Framework**. I would recommend to you to upgrade your project to the latest version of the framework. Here is a [short upgrade guide for `beta.4`](https://forum.ionicframework.com/t/ionic-2-projects-updating-to-beta-4/49054) but since you're upgrading from an older version you may need to perform additional steps _(in case that something is not working after the upgrade check out the breaking changes sections in the [changelog](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md) and perform the required updates)_.

**Comment by kevinnascimento** [comment]
@iignatov Thanks!
