### ISSUE TITLE
ionic info doesn't get OS (it returns empty)

### ISSUE THREAD

**Issue by cedms** [driftyco/ionic-cli#959]
Does anybody knows how can I get the the correct OS info? The "ionic info" command returns an empty field. I'm trying to use "push notifications" with no success and guessing this issue can be related. I'm using Windows 10.

c:\wamp\www\apps\app-005>ionic info
Your system information:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v4.2.0

**Comment by jthoms1** [comment]
Thanks for opening this issue. We are aware of the issue with Windows 10 no returning the correct OS in 'ionic info'.  This will be fixed in the next 2.0 beta release.

Have you opened an issue yet for the issue related to 'push notifications' on [ionic-platform-issues](https://github.com/driftyco/ionic-platform-issues)?

**Comment by cedms** [comment]
Ok, @jthoms1. Do you know when the 2.0 beta will be released?
About the push notifications issue, I'm not able to find it anymore. Actually I'm trying another ways to do that. Thanks.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
