### ISSUE TITLE
Ionic Serve error - "This site can't be reached." (v2)

### ISSUE THREAD

**Issue by eshansingh** [driftyco/ionic-cli#998]
OSX v.10.11.3 (beta)

So, I wanted to learn Ionic 2, so I did this:

> $ npm uninstall -g ionic # because I had ionic v1
$ npm i -g ionic@beta
$ ionic start MyApp tutorial --v2 --ts
$ ionic serve --lab

It worked. After I played around with it for a while, I deleted the `MyApp` directory. The very next day I did the same sequence of commands (except the first two because I didn't need to). But now Chrome was showing me a "This site can't be reached" error. I have confirmed this happens on other browsers too (tested with Chrome, Safari, and Firefox).  Both with and without the `--lab` option have the same issue. And this problem is reported only by the browser, ionic-cli doesn't seem to realize this, so there are no error messages on its end.

So then I be like, "You know what, I have a hunch...". You see recently I had installed the latest version of Node from their website (at the time of writing this is v6.1.0). However I quickly realized that 99.99% of everything I used was currently incompatible with Node 6, I uninstalled it following a guide I hade Googled. But before I had install Node v6 I actually had used [homebrew](http://www.brew.sh) to install node via `brew install node`, which installs Node v5. I did not remember that at the time, and after I uninstall Node v6, I installed the LTS version of Node, which is currently v4.4.4. So now I had all these different versions of Node.js on my system. So I thought, OK, maybe some shit happened with the versions. So I painstakingly uninstalled every version of node until I was sure there were practically no remnants of it (and Ionic) on my system. Then I did a complete reinstall of everything, Node v5 (using `brew`), Cordova, Typescript, Ionic, ios-sim, ios-deploy, etc. etc. etc.

Then I followed the same commands, and got the same error. So I was like "Damnit, this seems like some sort of bug or something." So here I am. 

Let me know if you need to know the specifics of what I did, as I know a lot of things could have gone wrong here.

**EDIT**: Output of ionic info for more information:

> Your system information:

> Cordova CLI: 6.1.1
Gulp version: CLI version 1.2.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by eshansingh** [comment]
See the short discussion over on the Ionic Forum: https://forum.ionicframework.com/t/ionic-serve-error-this-site-cant-be-reached-v2/51841/ for a little more oddities of this issue.

**Comment by jgw96** [comment]
Hello, as this seems like an issue with your local networking setup and not an issue with the cli i will be closing this issue. Thanks for using Ionic!

**Comment by ilya-payrange** [comment]
I encountered the same problem (This site can't be reached) with "npm i -g ionic@latest" as well as with "ionic@beta" on Windows 7, node.js 6.10.3, when trying "ionic start myApp tabs --type ionic1". BTW, "ionic serve" works fine in an app without "... --type ionic1". 

For posterity: what fixed the problem for me in --type ionic1 app when I started the server with this:
"ionic serve --address 127.0.0.1"

It did not matter for --lab (it looks like the server is the same, only URL open in the broswer is different, can be changed manually at any time).

It would be still nice if the issue was fixed, so documentation would work as stated, without resorting to forums at the "getting started" stage.

**Comment by adimittal** [comment]
Note: When running 2 ionic apps at the same time, it's not enough to specify a new port for the app, you also need to specify a new port for live reload and dev logger:
 ionic serve -p 8101 -r 8102 --dev-logger-port 8103 

Otherwise, you'll get this error.  Make sure firewall allows all those ports you use.
